#!/bin/bash

#Configuracion del scritp
#Definimos la ruta donde vamos a guardar el archivo .htpasswd
DirectorioHttpasswd=/home/usuario
httpusu=usuario
httppasswd=usuario
#Definimos la contraseña de root como variable
RootPasswdMysql=root

menu () {
clear
#MENU 
echo "*************"
echo "   MENÚ      "
echo "*************"
echo "1. Instalacion Lamp"
echo "2. Instalacion Herramientas Extras"
echo "3. Instalacion Configuracio GoAccess"
echo "4. Salir"
read -p "Elige una opción: " opcion

case $opcion in 
1)
    clear
    instalacion
    menu
    ;;
2)
    clear
    extra
    menu
    ;;
3)
    clear
    goaccess
    menu
    ;;
4)
    echo "Saliendo..."
    exit 0
    ;;

*)
    echo "error, saliendo"
    exit 1
    ;;
esac
}

instalacion() {

    #___________________________
    #INSTALACION LAMP
    #para depurar:
    set -x
    #Actualizamos los paquetes
    apt update
    apt upgrade -y
    #Instalacion Apache 
    apt install apache2 -y
    #Instalación MySQL 
    apt install mysql-server -y
    #Configuracion contraseña de root en MySQL
    export DEBIAN_FRONTEND="noninteractive"
    sudo apt-get install -y mysql-server-5.6
    mysql_secure_installation
    sudo debconf-set-selections < "mysql-server mysql-server/root_password password rootpw"
    sudo debconf-set-selections < "mysql-server mysql-server/root_password_again password rootpw"

    #read -p "introduzca usuario: " ususql   
    #read -p "introduzca contraseña: " passql
    #mysqladmin -u root -p  root < root
    #mysql -u root <<< "ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY '$RootPasswdMysql';" 
    #mysql -u root <<< "FLUSH PRIVILEGES;"

    #Instalacion PHP
    apt install php libapache2-mod-php php-mysql -y
}

extra() {
    #HERRAMIENTAS EXTRAS
    #Descargamos Adminer
    mkdir /var/www/html/adminer 
    cd /var/www/html/adminer 
    wget https://github.com/vrana/adminer/releases/download/v4.7.7/adminer-4.7.7-mysql.php 
    mv adminer-4.7.7-mysql.php index.php
    #Creación contraseña aleatoria para Adminer
    AUTOGENERATED_PASSWD=`tr -dc A-Za-z0-9 < /dev/urandom | head -c 64`
    #Configuracion instalación de phpMyAdmin
    echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2" | debconf-set-selections 
    echo "phpmyadmin phpmyadmin/dbconfig-install boolean true" | debconf-set-selections 
    echo "phpmyadmin phpmyadmin/mysql/app-pass password $AUTOGENERATED_PASSWD" |debconf-set-selections  
    echo "phpmyadmin phpmyadmin/app-password-confirm password $AUTOGENERATED_PASSWD" | debconf-set-selections
    #Instalamos phpMyAdmin
    apt install phpmyadmin php-mbstring php-zip php-gd php-json php-curl -y
    #Creación archivo info.php. Añadimos contenido 
    echo "<?php phpinfo (); ?>" > /var/www/html/info.php 

}

goaccess() {
    # Instalación de GoAccess
    echo "deb http://deb.goaccess.io/ $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/goaccess.list 
    wget -O - https://deb.goaccess.io/gnugpg.key | sudo apt-key add - 
    apt-get update 
    apt-get install goaccess -y

    # Creamos el directorio stats.
    mkdir /var/www/html/stats

    # Lazamos el proceso en segundo plano
    nohup goaccess /var/log/apache2/access.log -o /var/www/html/stats/index.html --log-format=COMBINED --real-time-html &
    htpasswd -c -b $DirectorioHttpasswd/.htpasswd $httpusu $httppasswd

    # Copiamos el archivo de configuracion de apache
    cp /home/ubuntu/000-default.conf /etc/apache2/sites-available/
    systemctl restart apache2   
    
}

menu